In [1]:
print("hello world!")

hello world!


In [7]:
import numpy as np  # type: ignore

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.random.rand(4,2)

array([[0.56089179, 0.03661006],
       [0.23031069, 0.881524  ],
       [0.84755221, 0.95700359],
       [0.19270523, 0.83854676]])

In [10]:
np.random.randint(-4, 8, size=(3,3))

array([[-2,  1,  3],
       [ 6,  1, -4],
       [ 6, -2, -2]], dtype=int32)

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [35]:
# fill an array with 5x5 1s on the border, zeros on the inside, and 9 in the middle
a1 = np.zeros((5,5))
a1[0] = 1
a1[4] = 1
a1[0,] = 1
a1[4] = 1
a1[2,2] = 9
print(a1)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [38]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# you can't do math operations on lists but can you do it to numpy arrays